version: 1
formatters:
  detailed:
    format: '%(asctime)s %(name)-15s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: data/logs/cryptobot.log
    when: midnight
    backupCount: 7
    level: DEBUG
    formatter: detailed

loggers:
  ccxt:
    level: WARNING
  telegram:
    level: INFO

root:
  level: DEBUG
  handlers: [console, file]